Summary component [WIP]
uwblueprint/wac-qualitative pull request #41
Opened 2019-06-07 07:19 UTC by jiang-austin

Finished summary component + page.

Still need to decide how to pass params, and clean up code

2019-06-07 07:21 UTC, jiang-austin commented
What the page currently looks like

<img width="1440" alt="Screen Shot 2019-06-07 at 3 20 34 AM" src="https://user-images.githubusercontent.com/17057747/59087657-4cd4c400-88d3-11e9-9f1e-114a4f72ac0c.png">

2019-06-07 20:59 UTC, suzyng83209 requested changes
Some of your Header work will be continued upon with my task. The original task wasn't very clear about the fact that the Header was a separate task but thanks for starting work on it!!

I requested changes on the way that the conditional rendering is handled though. If you take a look at my comment, it should include a useable example.

2019-06-07 20:59 UTC, suzyng83209 commented on src/components/Header.jsx
> +          </div>
Oh this Header stuff is something I'll was going to take on. This seems like a good direction though, I can build off of it.

2019-06-07 20:59 UTC, suzyng83209 commented on src/components/SummaryBox.jsx
> +export default SummaryBox;
It seems like there's some duplicated html elements in here.
Can you nest the selected child like:
```
<div className="figmaCard">
  <div className="boxboxbox">
    <h1 className="sectionNum"> Section {sectionNumber} </h1>
    <h1 className="sectionTitle"> {sectionTitle} </h1>
  </div>
  <div id="bar" />
  <div className={`outer-circle ${val == 0? 'red-b' : ''}`}>
    <div className="inner-circle">
      <p className={`circle-text ${val == 0? 'red-c' : ''}`}>
    ...
```

2019-06-07 20:59 UTC, suzyng83209 commented on src/components/SummaryBox.jsx
> +export default SummaryBox;
This is a way of passing in css classNames so your if statements generate the same html elements but with different styles.

2019-06-08 04:52 UTC, suzyng83209 approved these changes

2019-06-08 17:41 UTC, merged